#ifndef MB64_FACESHAPES_H
#define MB64_FACESHAPES_H

enum mb64_culling_shapes {
    MB64_FACESHAPE_FULL,
    MB64_FACESHAPE_POLETOP,

    MB64_FACESHAPE_TRI_1,
    MB64_FACESHAPE_TRI_2,
    MB64_FACESHAPE_DOWNTRI_1,
    MB64_FACESHAPE_DOWNTRI_2,
    MB64_FACESHAPE_HALFSIDE_1,
    MB64_FACESHAPE_HALFSIDE_2,

    MB64_FACESHAPE_TOPTRI,
    MB64_FACESHAPE_TOPHALF,

    MB64_FACESHAPE_BOTTOMSLAB_PRI = 0x10,
    MB64_FACESHAPE_UPPERGENTLE_1 = MB64_FACESHAPE_BOTTOMSLAB_PRI,
    MB64_FACESHAPE_UPPERGENTLE_2,
    MB64_FACESHAPE_BOTTOMSLAB,
    MB64_FACESHAPE_LOWERGENTLE_1 = MB64_FACESHAPE_BOTTOMSLAB_PRI + 4,
    MB64_FACESHAPE_LOWERGENTLE_2,

    MB64_FACESHAPE_TOPSLAB_PRI = 0x20,
    MB64_FACESHAPE_DOWNUPPERGENTLE_1 = MB64_FACESHAPE_TOPSLAB_PRI,
    MB64_FACESHAPE_DOWNUPPERGENTLE_2,
    MB64_FACESHAPE_TOPSLAB,
    MB64_FACESHAPE_DOWNLOWERGENTLE_1 = MB64_FACESHAPE_TOPSLAB_PRI + 4,
    MB64_FACESHAPE_DOWNLOWERGENTLE_2,

    MB64_FACESHAPE_EMPTY = 0x40,
    MB64_FACESHAPE_EMPTY_0,
    MB64_FACESHAPE_EMPTY_1,
    MB64_FACESHAPE_EMPTY_2,
    MB64_FACESHAPE_EMPTY_3,
};

#endif
